services:
  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    volumes:
      - ~/apps/postgres:/var/lib/postgresql/data
    env_file: "./.env"
  api: 
    build: 
      context: .
      dockerfile: ./backend/Dockerfile 
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db 
    ports: 
      - "5000:5000"
  streamlit:
    build:
      context: . 
      dockerfile: ./streamlit_app/Dockerfile 
    volumes: 
      - ./streamlit_app:/usr/src/app 
    ports:
      - "8501:8501"
    