services:
  api: 
    build: 
      context: ./backend 
      dockerfile: Dockerfile 
    volumes:
      - ./backend:/usr/src/app
    ports: 
      - "5000:5000"
  streamlit:
    build:
      context: ./streamlit_app
      dockerfile: Dockerfile 
    volumes: 
      - ./streamlit_app:/usr/src/app 
    ports:
      - "8501:8501"
    depends_on:
      - api 
    